# Generated by Django 3.2.4 on 2021-06-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_item_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='months',
            field=models.ManyToManyField(blank=True, null=True, to='customer.Month'),
        ),
    ]
