# Generated by Django 3.2.4 on 2021-06-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210627_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount_in_words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
