# Generated by Django 3.2.8 on 2021-10-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_item_amount_in_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kist',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
