# Generated by Django 3.2.8 on 2021-11-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_item_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cnic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
