# Generated by Django 3.2.9 on 2021-11-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_item_total_kist_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hbl', max_length=255)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
